-- MySQL Script generated by MySQL Workbench
-- Fri Apr  1 19:16:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AID_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AID_DB
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `AID_DB` DEFAULT CHARACTER SET utf8 ;
USE `AID_DB` ;

-- -----------------------------------------------------
-- Table `AID_DB`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AID_DB`.`USER` (
  `Serial_Number` VARCHAR(12) NOT NULL,
  `ID` INT NOT NULL,
  `PW` INT NOT NULL,
  `Name` VARCHAR(10) NOT NULL,
  `Age` TINYINT(1) NOT NULL,
  `Address` VARCHAR(90) NOT NULL,
  `Number` VARCHAR(13) NOT NULL,
  `Log_Path` VARCHAR(23) NOT NULL,
  PRIMARY KEY (`Serial_Number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AID_DB`.`Manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AID_DB`.`MANAGER` (
  `ID` INT NOT NULL,
  `PW` INT NOT NULL,
  `USER_Serial_Number` VARCHAR(12) NOT NULL,
  `Name` VARCHAR(10) NOT NULL,
  `Relationship` ENUM("Family", "Agency") NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Number` VARCHAR(13) NOT NULL,
  INDEX `fk_Protector_USER_idx` (`USER_Serial_Number` ASC) VISIBLE,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_Protector_USER`
    FOREIGN KEY (`USER_Serial_Number`)
    REFERENCES `AID_DB`.`USER` (`Serial_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------------------------------
-- Insert default data
-- -----------------------------------------------------
INSERT INTO USER 
VALUES ('AAA000000001', 12345, 54321, '김할머니', 70, '대한민국 어딘가', '010-1234-5678', './Log/AAA000000001.json');

INSERT INTO MANAGER 
VALUES (369, 963, 'AAA000000001', '가족', 'Family', 'whtkddus98@kookmin.ac.kr', '010-4321-5678');

INSERT INTO MANAGER 
VALUES (123, 321, 'AAA000000001', '기관', 'Agency', '12345@ABCDEFG.com', '010-9876-5432');
