-- MySQL Script generated by MySQL Workbench
-- Wed Mar 30 11:47:31 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AID_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AID_DB
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `AID_DB` DEFAULT CHARACTER SET utf8 ;
USE `AID_DB` ;

-- -----------------------------------------------------
-- Table `AID_DB`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AID_DB`.`USER` (
  `USER_ID` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(16) NOT NULL,
  `Serial_Number` VARCHAR(12) NOT NULL,
  `Name` VARCHAR(8) NOT NULL,
  `Age` TINYINT(1) NOT NULL,
  `Address` VARCHAR(90) NOT NULL,
  `Relationship_1_Name` VARCHAR(32) NULL,
  `Relationship_1` TINYINT NOT NULL,
  `Relationship_1_Number` VARCHAR(45) NOT NULL,
  `Relationship_2_Name` VARCHAR(32) NULL,
  `Relationship_2` TINYINT NULL,
  `Relationship_2_Number` VARCHAR(45) NULL,
  `Relationship_3_Name` VARCHAR(32) NULL,
  `Relationship_3` TINYINT NULL,
  `Relationship_3_Number` VARCHAR(45) NULL,
  PRIMARY KEY (`USER_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AID_DB`.`LOG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AID_DB`.`LOG` (
  `LOG_ID` BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `USER_USER_ID` VARCHAR(45) NOT NULL,
  `Time_stemp` DATETIME(3) NULL,
  `Emotion` ENUM("Happiness", "Sadness", "Anger", "Anxiety") NULL,
  `Text_path` TEXT(64) NULL,
  PRIMARY KEY (`LOG_ID`),
  INDEX `fk_LOG_USER_idx` (`USER_USER_ID` ASC) VISIBLE,
  CONSTRAINT `fk_LOG_USER`
    FOREIGN KEY (`USER_USER_ID`)
    REFERENCES `AID_DB`.`USER` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
