-- MySQL Script generated by MySQL Workbench
-- Sat May 14 19:22:48 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema aid_db
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema aid_db_2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aid_db_2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aid_db_2` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `aid_db_2` ;

-- -----------------------------------------------------
-- Table `aid_db_2`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aid_db_2`.`user` (
  `Serial_Number` VARCHAR(12) NOT NULL,
  `ID` VARCHAR(24) NOT NULL,
  `PW` VARCHAR(24) NOT NULL,
  `Name` VARCHAR(10) NOT NULL,
  `Age` TINYINT(1) NOT NULL,
  `Address` VARCHAR(90) NOT NULL,
  `Number` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`Serial_Number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aid_db_2`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aid_db_2`.`log` (
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `emotion` VARCHAR(20) NOT NULL,
  `talk` VARCHAR(100) NOT NULL,
  `user_Serial_Number` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`date`, `user_Serial_Number`),
  INDEX `fk_log_user1_idx` (`user_Serial_Number` ASC) VISIBLE,
  CONSTRAINT `fk_log_user1`
    FOREIGN KEY (`user_Serial_Number`)
    REFERENCES `aid_db_2`.`user` (`Serial_Number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aid_db_2`.`manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aid_db_2`.`manager` (
  `ID` VARCHAR(24) NOT NULL,
  `PW` VARCHAR(24) NOT NULL,
  `Name` VARCHAR(10) NOT NULL,
  `Relationship` ENUM('Family', 'Agency') NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Number` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aid_db_2`.`manager_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aid_db_2`.`manager_has_user` (
  `manager_ID` VARCHAR(24) NOT NULL,
  `user_Serial_Number` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`manager_ID`, `user_Serial_Number`),
  INDEX `fk_manager_has_user_user1_idx` (`user_Serial_Number` ASC) VISIBLE,
  INDEX `fk_manager_has_user_manager_idx` (`manager_ID` ASC) VISIBLE,
  CONSTRAINT `fk_manager_has_user_manager`
    FOREIGN KEY (`manager_ID`)
    REFERENCES `aid_db_2`.`manager` (`ID`),
  CONSTRAINT `fk_manager_has_user_user1`
    FOREIGN KEY (`user_Serial_Number`)
    REFERENCES `aid_db_2`.`user` (`Serial_Number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
