-- MySQL Script generated by MySQL Workbench
-- Fri Apr  1 19:16:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AID_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AID_DB
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `heroku_d4b1a4548f6a83d` DEFAULT CHARACTER SET utf8 ;
USE `heroku_d4b1a4548f6a83d` ;

-- -----------------------------------------------------
-- Table `AID_DB`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_d4b1a4548f6a83d`.`USER` (
  `Serial_Number` VARCHAR(12) NOT NULL,
  `ID` VARCHAR(24) NOT NULL,
  `PW` VARCHAR(24) NOT NULL,
  `Name` VARCHAR(10) NOT NULL,
  `Age` TINYINT(1) NOT NULL,
  `Address` VARCHAR(90) NOT NULL,
  `Number` VARCHAR(13) NOT NULL,
  `Log_Path` VARCHAR(23) NOT NULL,
  PRIMARY KEY (`Serial_Number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AID_DB`.`Manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_d4b1a4548f6a83d`.`MANAGER` (
  `ID` VARCHAR(24) NOT NULL,
  `PW` VARCHAR(24) NOT NULL,
  `USER_Serial_Number` VARCHAR(12) NOT NULL,
  `Name` VARCHAR(10) NOT NULL,
  `Relationship` ENUM("Family", "Agency") NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Number` VARCHAR(13) NOT NULL,
  INDEX `fk_Protector_USER_idx` (`USER_Serial_Number` ASC) VISIBLE,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_Protector_USER`
    FOREIGN KEY (`USER_Serial_Number`)
    REFERENCES `AID_DB`.`USER` (`Serial_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------------------------------
-- Insert default data
-- -----------------------------------------------------
-- w40FGR81kYGlvhdxKR5m3w== -> user1_id
-- avZJNl8NWKBMWEey4W38Cg== -> user1_pw
INSERT INTO USER 
VALUES ('AAA000000001', 'w40FGR81kYGlvhdxKR5m3w==', 'avZJNl8NWKBMWEey4W38Cg==', '김할머니', 70, '대한민국 어딘가', '010-1234-5678', './Log/AAA000000001.json');


-- gsurIXUZdIuFJcxFpGKNFQ== -> manager1_id
-- fqyarXKn1/hjRkAgVNCXCw== -> manager1_pw
INSERT INTO MANAGER 
VALUES ('gsurIXUZdIuFJcxFpGKNFQ==', 'fqyarXKn1/hjRkAgVNCXCw==', 'AAA000000001', '가족', 'Family', 'whtkddus98@kookmin.ac.kr', '010-4321-5678');

-- txJRKXyIVfyhtVzNBdyCug== -> manager2_id
-- hXdCGi0t0MTYJrnpSdvHBg== -> manager2_pw
INSERT INTO MANAGER 
VALUES ('txJRKXyIVfyhtVzNBdyCug==', 'hXdCGi0t0MTYJrnpSdvHBg==', 'AAA000000001', '기관', 'Agency', '12345@ABCDEFG.com', '010-9876-5432');